# Generated by Django 5.1.5 on 2025-01-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spofify_integration', '0002_genre_artist_artist_id_alter_artist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
